### PR TITLE
Update local url to scanapi.dev

### PR DESCRIPTION
**Pull request by marcorichetta**
I assume this url needs to point out to the main site.
Feel free to correct me!

### CODE REVIEW

**Review by barbosa — APPROVED** [review]
Nice catch!

**Comment by camilamaia** [comment]
@marcorichetta Congrats for your first PR merged! Thank you very much!

I am going to send you an invite to join the ScanAPI org on GitHub 🚀 We invite everyone that has contributed with a merged PR in any of our repos. Here you can check our [Contributing Guidelines](https://github.com/scanapi/contributors/blob/main/CONTRIBUTING.md) so you can understand better how it works.

And once again, thank you! 🙇‍♀️

**Comment by Pradhvan** [comment]
@marcorichetta thanks for the PR! Come join our community in Discord too. 🙌🥳

 https://discord.gg/jzCW3kcV

**Comment by marcorichetta** [comment]
Thank you both! :smile: @camilamaia @Pradhvan

**Pull request merged**
