### PR TITLE
Fix scape of ${{}}

### LINKED ISSUE #18: Hide Tutorial Links
## Hide Tutorial Links

While we don't have a tutorial, it would be nice to hide the Tutorial links to avoid confusion.

image

image

### LINKED ISSUE #23: Add examples link to the Menu
## Add examples link to the Menu

Add a menu `Examples` that links to our examples repository: https://github.com/scanapi/examples

image

https://github.com/scanapi/website/blob/master/_includes/navigation.html

### PR DESCRIPTION
**Pull request by camilamaia**
## Fix scape of ${{}}
**Before**
image

**After**
image

Also:

- Hide Tutorial Links
- Add examples menu link
- Add codeowners

Closes #18 
Closes #23

### CODE REVIEW

**Comment by abreumatheus** [comment]
@camilamaia I think we should also have the basic usage section in the site, so when the user clicks on "Docs" that's the first section they see, instead of the "Configuration File" section. I'm suggesting this because there is a possibility that the user will never come here to the repo.

**Comment by camilamaia** [comment]
@abreumatheus definitely! Also, the order of the pages are still not right at all. We need to set it with jekyll. It would be nice to have a root url too, like `\docs`. We need to improve a lot the docs in the website. Totally agreed!

**Comment by camilamaia** [comment]
@abreumatheus I've created a PR that fixes the problem you pointed out: https://github.com/scanapi/website/pull/28

**Comment by abreumatheus** [comment]
> @abreumatheus I've created a PR that fixes the problem you pointed out: https://github.com/scanapi/website/pull/28

Nice! 😃

**Pull request merged**
